theme: jekyll-theme-minimal
font-icon: /assets/css/font-awesome-4.7.0/css/font-awesome.min.css

# 你的求职方向，比如前端开发工程师等
title:Java开发工程师/搜索系统工程师/AI研发工程师

# 对你自己的简洁描述
description:熟悉Java和Python的程序员，熟悉搜索系统，对大模型应用具有浓厚的兴趣，落地过大模型应用。

# 你的美照地址
logo: /assets/images/me.jpg

# 你的名字
name:程利伟

# 你的联系方式
phone:15311436841

# 你的邮箱
email:413555021@qq.com

# 你目前的住址
address:北京朝阳

# 你毕业院校
school:北方工业大学

# 你的专业
profession:软件工程

# 你的学位
degree:硕士

